# Setup
title:               LI Yinqiao's Homepage
tagline:             'A researcher in Natural Language Processing (NLP).'
description:         LI Yinqiao's Homepage
url:                 'https://liyinqiao2012.github.io'
baseurl:             ''
# paginate:            5
permalink:           pretty

# About/contact
author:
  name:              LI Yinqiao
  email:             li.yin.qiao.2012@hotmail.com

# Gems
#plugins:
#  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
